### ISSUE TITLE
Google Tag Assistant Chrome extension unusable with recompose?

### ISSUE THREAD

**Issue by TrevorHinesley** [acdlite/recompose#631] opened 2018-03-23 15:33 UTC
We're having a strange issue with a new build of our React front-end. We decided to use Recompose to slim things down, but now the entire development build freezes and is fully unresponsive *ONLY* if Google's Tag Assistant extension is enabled. The old production app (basically the exact same logic minus recompose) works fine with this extension enabled. Nothing has changed about any of our Google snippets or AdWords related event tracking either. Has anyone experienced anything like this? We're able to reproduce it consistently on multiple computers.

**Comment by istarkov** [comment] 2018-04-12 00:04
Just run profiler from chrome dev tools and check what the problem is. It can be anything and I'm pretty sure that it's not the recompose issue. Recompose does not use global variables, it does not render anything etc.
I'll close this as without example, profile logs, etc, this issue will never be solved.

**Closed by istarkov** 2018-04-12 00:04 UTC
