### ISSUE TITLE
Make it possible to pick nested objects

### ISSUE THREAD

**Issue by tsm91** [acdlite/recompose#188] opened 2016-06-02 14:08 UTC
Hello @acdlite, in [pick](https://github.com/acdlite/recompose/blob/master/src/packages/recompose/utils/pick.js) it is not possible to get nested objects.

I tend to namespace the actions and state wrapped by `connect`. 

So a stateless component could receive props shape like this:

```js
{
  state: {
    container1: { ... },
    container2: { ... }
  },
  actions: {
    container1: { ... },
    container2: { ... }
  }
}

// ...

// this wont work, because you cannot select nested objects with the current implementation of `pick`
onlyUpdateForKeys(['actions.todos', 'state.todos'])(App);
```

**Comment by istarkov** [comment] 2016-06-02 14:12
Please read https://github.com/acdlite/recompose/issues/166
As mostly this issue is a duplicate.

**Comment by acdlite** [comment] 2016-06-06 16:56
As @istarkov says, this is a duplicate of #166.

**Closed by acdlite** 2016-06-06 16:56 UTC
