### ISSUE TITLE
Decorator breaks enzyme tests

### ISSUE THREAD

**Issue by AvraamMavridis** [acdlite/recompose#313] opened 2017-02-09 12:52 UTC
Example:

```
@pure
class A extends Component {
  aMethod(){}
}
```

```
const wrapper = mount(<A />);
wrapper.instance().aMethod() // Error, Cannot read property aMethod of undefined
```

**Comment by istarkov** [comment] 2017-02-09 13:10
You wrap one component with other component using pure enhancer, why you expect that instance methods of internal component will be available on upper instance?
It is expected behavior.

**Comment by AvraamMavridis** [comment] 2017-02-09 13:12
@istarkov I was expecting to not affect the tests, but probably I am wrong.
Is it a way to access the method, although the component is wrapped?

**Comment by istarkov** [comment] 2017-02-09 13:19
Almost all recompose enhancers generates Hight Order Component - wrapper, 
in `pure` case it's some kind of 
```
class B extends Component {
   shouldComponentUpdate {
      shallowEqual ...
   }
   render() {
       return <A {...this.props} />; // Here A is your component
   }
}
```

real code [pure](https://github.com/acdlite/recompose/blob/master/src/packages/recompose/pure.js#L5) uses 
[shouldUpdate](https://github.com/acdlite/recompose/blob/master/src/packages/recompose/shouldUpdate.js)

**Comment by wuct** [comment] 2017-02-28 09:04
I'm going to close this issue because it's not a bug.

**Closed by wuct** 2017-02-28 09:04 UTC
