### ISSUE TITLE
Initialization and  withState vs withStateHandlers

### ISSUE THREAD

**Issue by lishine** [acdlite/recompose#578] opened 2017-12-21 06:12 UTC
Thanks for your great library!
I am building with it almost every component :)

1. Strange to me behaviour of state, described below
2. The initialization differs between withState and withStateHandlers. (I read the recomendation to use withStateHandlers)
3. What is the recommended way to init state - in withStateHandler or in constructor lifecycle or in componentDidMount or in componentWillMount ?

```javascript
export default compose(
	withStateHandlers(
		() => ({
			data: [],
		}), {
			setData: () => data => ({ data }),
		}
	),
	// withState('data', 'setData', []),
	withState('notif', 'setNotif', undefined),
	withState('initialized', 'setInitialized', undefined),
	lifecycle({
		async componentDidMount() {
			const p = this.props;
			this.notificationListener = FCM.on(FCMEvent.Notification, notif => p.setNotif(notif));
			console.log('home mounted');

			console.log('p.data');
			console.log(p.data);

			const data = await LocalStorage.get('data');
			if (data) p.setData(data);

			FCM.getInitialNotification().then(notif => p.setNotif(notif));

			p.setInitialized(false);
		},
```

React native. Firebase notifications.
The sequence:
1. data has data from notifications
2. setData([]) - Initiated by a user
3. The data confirmed to be []
4. App is minimized by a user
5. App opened from minimized by a notification.
6. App seems to remount.

- When using withState - data in componentDidMount somehow gets value of before setting to [].
- When using withStateHandlers - the data is []

**Comment by istarkov** [comment] 2017-12-21 07:12
Hi, you need to at least show numeration of your steps,  as at what place data somehow gets value? And better to provide reproducible example at jsbin, codesandbox etc without all that react native, local storage etc.
Also why are you name setState change of a state as a initialisation, initialisation is providing initial value to state, its different from updating.
IMO the reason you have different values because withStateHandlers uses internally functional form of setState and withState is not. Functional form of setState have a different behaviour in some situation.

**Comment by wuct** [comment] 2018-02-24 11:00
I'm going to close this issue because there is not too much we can do here. Please feel free to reopen it if you can provide more detail for us to help you.

**Closed by wuct** 2018-02-24 11:00 UTC
