### ISSUE TITLE
Using react-with-styles in recompose

### ISSUE THREAD

**Issue by niranjanshukla** [acdlite/recompose#572] opened 2017-12-07 18:55 UTC
Can someone help me with an example of applying styles using react-with-styles in a higher order component using recompose ?

Specifically, how can we apply styles as explained in this example -- https://github.com/airbnb/react-with-styles -- in a higher order recompose wrapper ?

**Comment by istarkov** [comment] 2017-12-07 19:05
As any other HOC.
```
compose(
  hoc1, hoc2, withStyles(({ color }) => ({....}), hocN
)
```

**Comment by niranjanshukla** [comment] 2017-12-07 19:15
@istarkov Thanks. I tried it the way you mentioned above and specifically, I am stuck at understanding how the styles of DateRangePicker (the component whose style I am trying to override) are to be set inside withStyles.

I set styles as mentioned in the theming snippet [](https://github.com/airbnb/react-dates#theming) , imported withStyles in HOC and am trying to override styles of DateRangePicker below:

recompose(
hoc1,
hoc2,
withStyles(({ reactDates }) => ({
    //What is the approach to overriding styles of DateRangePicker ?
  }))
)(DateRangePicker)

**Comment by istarkov** [comment] 2017-12-07 19:55
I have no idea how to use `withStyles` as I use different style managers. In case of react-dates I use styled-components and override them as
```javascript
const datePickerStyles = `
  .CalendarMonthGrid {
    font-size: 14px;
  }

  .CalendarMonth_caption {
    font-size: 14px;
    line-height: 28px;
  }

  /* Info panel support */
  .DayPicker {
    width: unset !important;
    > div {
      display: grid;
      /*grid-template-columns: auto auto;
      grid-template-rows: auto; */
    }
  }

  .DayPicker_weekHeaders {
    grid-column-start: 2;
    grid-column-end: 2;
    grid-row-start: 1;
    grid-row-end: 1;
  }

  .DayPicker_focusRegion {
    grid-column-start: 2;
    grid-column-end: 2;
    grid-row-start: 1;
    grid-row-end: 1;
  }
  .DateInput__openDown {
    :before {
      top: 42px;
    }

    :after {
      top: 43px;
    }
  }

  .DateInput__openUp {
    :before {
      top: -14px;
    }

    :after {
      top: -15px;
    }

  }

  .SingleDatePicker_picker__openDown {
    top: 53px;
  }

  .SingleDatePicker_picker__openUp {
    bottom: 49px;
  }

  .DayPickerNavigation_button__horizontal {
    border: none;
    top: 20px;
  }

  .CalendarDay_container {
    border: none;
    &:hover {
      border: none;
    }
  }

  .CalendarDay__selected {
    border: none;
    border-color: #3f51b5;
    background-color: #3f51b5;
  }

  .CalendarDay__selected:active, .CalendarDay__selected:hover  {
    border-color: #7986CB;
    background-color: #7986CB;
  }

  .CalendarDay__selected_span {
    border: none;
    border-color: #5c6bc0;
    background-color: #5c6bc0;
  }

  .CalendarDay__selected_span:active, .CalendarDay__selected_span:hover  {
    border-color: #7986CB;
    background-color: #7986CB;
  }

  .CalendarDay__hovered_span {
    border: none;
    border-color: #9fa8da;
    background-color: #9fa8da;
    color: #3f51b5;
  }

  .CalendarDay__hovered_span:active, .CalendarDay__hovered_span:hover  {
    border-color: #9fa8da;
    background-color: #9fa8da;
    color: #3f51b5;
  }

`;

const Label = styled.div`
  pointer-events: none;
  color: ${({ focusedInput }) =>
    focusedInput ? 'rgb(48, 79, 254)' : 'rgba(0, 0, 0, 0.54)'};
  position: absolute;
  left: 0;
  top: 22px;
  transition: all ${ANIM_TIMEOUT}ms cubic-bezier(0.4, 0, 0.2, 1);
  transform-origin: 0% 50%;
  transform: ${({ focusedInput, value }) =>
    focusedInput || value
      ? `translate(0, ${-24}px) scale(0.75);`
      : 'translate(0,0) scale(1);'};
`;

const UFormHelperText = styled(FormHelperText)`
  && {
    position: absolute;
  }
`;

const DateRangeDiv = styled.div`
  & {
    width: 100%;
    position: relative;
    ${datePickerStyles};
  }
`;
```

Then react-dates placed as child of `DateRangeDiv` got my styled

**Comment by niranjanshukla** [comment] 2017-12-07 21:02
Thanks ! Looks like my question sits midway between recompose and Theming as applied to react-dates. Any general example on how to override styling in a recompose wrapper component would be great.

**Comment by wuct** [comment] 2017-12-10 14:28
@niranjanshukla Perhaps you should create a question at StackOverflow?

**Comment by wuct** [comment] 2017-12-10 14:30
Because it's not a bug report or a feature request, so I'm going to close this issue. Please feel free to reopen it if you have any further thought.

**Closed by wuct** 2017-12-10 14:30 UTC
