### ISSUE TITLE
[HOC suggestion] withStyles

### ISSUE THREAD

**Issue by PeteJodo** [acdlite/recompose#256] opened 2016-10-04 16:02 UTC
`withStyles` is probably a misnomer since it implies the `style` prop for the basic components. Regardless, I find having to remember CSS classes and SCSS variables to be annoying in large codebases. I feel like it can lead to bloated CSS due to multiple people creating 2 different classes to style similar things.

I was thinking you can abstract the use of CSS into HOCs that just extend `className` but would also let you build onto it. For a contrived example...

``` jsx
const colorPrimary = withStyles('some-class');
const colorPrimaryButton = withStyles(
  colorPrimary,
  'another-class'
);

const PrimaryComponent = colorPrimary(SomeComponent);
const PrimaryButton = colorPrimaryButton(DOM.button);
const PrimaryLink = colorPrimaryButton(DOM.link)
```

I wrote [this gist](https://gist.github.com/PeteJodo/2c88a608643ae63fe8c0fcbb26ca0838) originally with just `withProps` but then realized that if you want to create a hierarchy, then an allocation would be made for each call to `withProps` so I wrote a somewhat naive implementation of `withStyles` there. I would like to hear others' opinions on the concept and the implementation.

**Comment by istarkov** [comment] 2016-10-04 16:08
There are many different styles libraries available over the github.
For example now I use `css-modules` with [themr](https://github.com/javivelasco/react-css-themr) library.
Isn't it will be better to use all that fantastic enhancers of such libraries to solve styling problem?

**Comment by PeteJodo** [comment] 2016-10-04 16:26
I have not heard of `themr` to be honest, will check it out

**Comment by kevinSuttle** [comment] 2016-10-26 21:35
The problem is that it seems you're forced to write a wrapper if you want to tackle this yourself. http://stackoverflow.com/questions/40271866/inject-new-inline-styles-to-a-react-hoc-product

**Comment by therealparmesh** [comment] 2016-12-09 20:38
+1 for [react-css-themr](https://github.com/javivelasco/react-css-themr)

**Comment by wuct** [comment] 2017-02-28 10:23
I am going to close this issue because it's apparently not in the scope of recompose.

**Closed by wuct** 2017-02-28 10:23 UTC
