### ISSUE TITLE
withState() updater does nothing above withPropsWithChange

### ISSUE THREAD

**Issue by realalexhomer** [acdlite/recompose#641] opened 2018-04-06 02:33 UTC
Hi, I have spent a good part of today going completely insane figuring out why my withState updaters weren't doing anything. I haven't peeked at the source code that might be causing this but this certainly seems like a bug.

Plunkr here: http://plnkr.co/edit/P6Vhq98ShiUJ1L6N0WrE?p=preview

And I made a github repo you can clone and play around with more easily here: 

https://github.com/realalexhomer/recompose-with-state-bug

The gist of this issue is that when you have a `withState` function composed above a `withPropsOnChange` function, and the `withPropsOnChange` function maps props, the `withState` handler will not update state. It will get mapped to props, but invoking it does nothing. I'm guessing the `this` it is referencing is incorrect.

For the example I invoked it on a handler created with `withHandlers`, but this can just as easily be invoked in any other callback ( I was originally doing it in apollo callbacks) or in a `withStateHandler`, etc.

I think the plunkr / repo speak for themselves, please let me know if theres anything else I can do to help get this fixed. 

Thanks! 😁

**Comment by istarkov** [comment] 2018-04-06 06:44
You disable all updates in withPropsOnChange, and override all props there, so no updates are visible since then. 
As withPropsOnChange always return cached version.
Its expected behaviour and not a bug. Just return props you need, so cached props will be merged with props.

**Closed by istarkov** 2018-04-06 06:44 UTC

**Comment by realalexhomer** [comment] 2018-04-09 15:01
I understand that from your perspective this would be the expected behavior, but I would be surprised if many of the longterm users of this library would be able to foresee this bug given the[ code sample](http://plnkr.co/edit/P6Vhq98ShiUJ1L6N0WrE?p=preview) I provided. Once you see it in isolation is makes sense (sort of), but based on the [documentation](https://github.com/acdlite/recompose/blob/master/docs/API.md#withprops) this is not something in my opinion a reasonable user of the library would expect.

Would it be possible for us to either 

a) document the behavior as a known gotcha of the pattern in `withHandlers` or `withPropsOnChange`

or 

b) make it impossible for a handler not to lose its reference to the parent component, or at the very least fire a warning when this happens? Or fire a warning if a handler is called using an outdated `setState`?

I'd be very happy to submit a PR based on your feedback, just please let me know what you think is the solution and if you'd be willing to take another look this 😄 

Thanks!!

**Comment by istarkov** [comment] 2018-04-09 15:14
withPropsOnChange exists 1 or 2 years, and you are the first with this issue ;-)  
imo if updates are disabled and you override all the props - what other result it can be ;-) 
Im not sure about what warning are you talking, as code above can be used to freeze all the props in some code, so its not bug or any issue.

btw you can improve the docs and if it will be better we will accept PR
