### ISSUE TITLE
[0.25.0 update] createEagerFactory production only error

### ISSUE THREAD

**Issue by dlebedynskyi** [acdlite/recompose#489] opened 2017-08-21 21:59 UTC
after update to 0.25.0 start getting 
```
Error walking your react tree
TypeError: Class constructor OnMount cannot be invoked without 'new'
at createEagerElementUtil (/app/node_modules/recompose/utils/createEagerElementUtil.js:18:12)
at /app/node_modules/recompose/createEagerFactory.js:18:49
at ShouldUpdate.render (/app/node_modules/recompose/shouldUpdate.js:45:16)
at /app/node_modules/react-tree-walker/commonjs/index.js:148:35
at doTraverse (/app/node_modules/react-tree-walker/commonjs/index.js:78:21)
```
was all fine on 0.24.0 

OnMount component is pretty plain 
```
export default (timeout = 0) => BaseComponent =>
  class OnMount extends PureComponent {
    state = { isMounted: false };

    componentDidMount() {
      this.mounted = true;
      setTimeout(() => {
        if (this.mounted) {
          this.setState({ isMounted: true });
        }
      }, timeout);
    }

    componentWillUnmount() {
      this.mounted = false;
    }

    mouted = false;

    render = () =>
      <BaseComponent isMounted={this.state.isMounted} {...this.props} />;
  };

```

**Comment by istarkov** [comment] 2017-08-21 22:18
Can you provide a full example on [jsbin](https://jsfiddle.net/samsch/p3vsmrvo/2/)? 
As I'm not see `createEagerElementUtil` in your code above.
Is it reproduced in DEV only mode or also in production?

cc @deepsweet

**Comment by dlebedynskyi** [comment] 2017-08-21 22:30
@istarkov 
only on production. Dev runs fine.  https://jsfiddle.net/p3vsmrvo/3/

**Comment by istarkov** [comment] 2017-08-21 22:34
That change haven't change anything in production mode, seems like this https://github.com/acdlite/recompose/pull/463/files

**Comment by dlebedynskyi** [comment] 2017-08-21 22:47
a bit more debugging. 
I'm getting 
```
type is  class OnMount extends _react.PureComponent {
// ..
```
from 
```
var createEagerElementUtil = function createEagerElementUtil(hasKey, isReferentiallyTransparent, type, props, children) {
  if (!hasKey && isReferentiallyTransparent) {
    if (children) {
      return type(_extends({}, props, { children: children }));
    }
    console.log('type is ', type, props);
    return type(props);
  }
```
and if I try something like  stuff this 
```
const hoc = compose(
  pure,
  setPropTypes(propTypes),
  createEagerElement(onMount(), {}),

```
getting same error 
```
TypeError: Class constructor OnMount cannot be invoked without 'new'
 at ../recompose/compose.js:22:18
```

**Comment by istarkov** [comment] 2017-08-21 22:49
I just run that example in production mode and in development and see no error
Here is full example 
```javascript
import { compose } from 'recompose'
import React from 'react'
import ReactDOM from 'react-dom'

const onMount = (timeout = 0) => BaseComponent =>
  class OnMount extends React.PureComponent {
    state = { isMounted: false }

    componentDidMount() {
      this.mounted = true
      setTimeout(() => {
        if (this.mounted) {
          this.setState({ isMounted: true })
        }
      }, timeout)
    }

    componentWillUnmount() {
      this.mounted = false
    }

    mouted = false

    render = () =>
      <BaseComponent isMounted={this.state.isMounted} {...this.props} />
  }

const Counter = ({ count, increment, decrement }) =>
  <div>
    Count: {count}
    <div>
      <button onClick={increment}>+</button>
      <button onClick={decrement}>-</button>
    </div>
  </div>

const App = compose(onMount())(Counter)

ReactDOM.render(<App />, document.getElementById('root'))
```

I used create-react-app to build and run

**Comment by istarkov** [comment] 2017-08-21 22:53
Your React version?

**Comment by istarkov** [comment] 2017-08-21 22:54
Also in example you provided, again no eager factory is used

**Comment by istarkov** [comment] 2017-08-21 23:01
But I'm able to reproduce it adding `pure` HOC in compose

**Comment by istarkov** [comment] 2017-08-21 23:34
Minimal example to reproduce
```
import { compose, pure } from 'recompose'
import React from 'react'
import ReactDOM from 'react-dom'

const onMount = (timeout = 0) => BaseComponent =>
  class OnMount extends React.Component {
    render = () => <BaseComponent {...this.props} />
  }

const Counter = ({ count, increment, decrement }) => <div>HELLO</div>

const App = compose(pure, onMount())(Counter)

class Hello extends React.PureComponent {
  render() {
    return <div />
  }
}

ReactDOM.render(<App />, document.getElementById('root'))
```

**Comment by istarkov** [comment] 2017-08-21 23:36
To fix don't bind render method
```javascript
const onMount = (timeout = 0) => BaseComponent =>
  class OnMount extends React.Component {
    render() {
      return <BaseComponent {...this.props} />
    }
  }
```

**Comment by istarkov** [comment] 2017-08-22 11:45
I'll close this, feel free to reopen
If you are interesting about what the problem with bind and why it occurred now:
It is combination of 2 PRs #473 and #463 
To check that component is a React Class Component we started to check the existence of render method in Component prototype in #463 and then in #473 we disabled that check used for optimisation purposes in DEV mode. So at production we get stuck. 
I'm not sure do we need to provide an additional check that if type is not a react class it must be function. Imo yes it will be better to provide such check in devmode.
cc @wuct @deepsweet  You thoughts?

**Comment by deepsweet** [comment] 2017-08-22 11:54
I think that the concept mentioned in #473 is correct and we shouldn't rely on any "post-production" optimizations in any way. Something should be done on `isClassComponent` side, like "an additional check that if type is not a react class it must be function" you mentioned.

**Comment by dlebedynskyi** [comment] 2017-08-22 13:50
@istarkov thanks for explaining this. 
My main frustration is that it runs ok in development while crushes on production. This is not desired behavior and can lead to 'wtf' issues  on production. I'd personally prefer not to have this optimization then have unexpected behavior. 
@deepsweet idea might be good option to look into

**Comment by wuct** [comment] 2017-08-23 06:18
@istarkov I can't reproduce the problem using your minimal code. Here is [the jsbin](https://jsfiddle.net/dm7uzmxq/). Do I miss something?

**Comment by istarkov** [comment] 2017-08-23 07:31
@wuct  production only bug

**Comment by pk-nb** [comment] 2017-09-20 15:58
Could we reopen this bug? We got burned by this as well. We use `render = () =>` in lots of places it's breaking with `mapProps`

**Comment by istarkov** [comment] 2017-09-20 16:07
Just stop bind render method. There is no sense in this at all.

**Comment by dlebedynskyi** [comment] 2017-09-26 14:45
> Just stop bind render method. There is no sense in this at all.
@istarkov it does really make much sense to prevent doing that. For purpose of recompose not to crush on production suddenly. 
Even if we fix that there is not guaranty that someone won't do it again for whatever reason just to break only production build. 
Imo it is better without this change then having only production bugs.

**Comment by istarkov** [comment] 2017-09-26 14:55
IMO its better without this optimizations too. Let us think a little what to do. May be we can provide additional checks at dev mode or something else cc @deepsweet

**Comment by istarkov** [comment] 2017-09-26 14:56
Any help will be very appreciated.

**Comment by deepsweet** [comment] 2017-09-26 15:01
I'd like to somehow extract this optimization from Recompose at all.

**Comment by wuct** [comment] 2017-09-27 07:15
I agree it's better to leave this optimization to React.

**Comment by deepsweet** [comment] 2017-10-02 08:56
so... let's remove it then? :)

**Comment by istarkov** [comment] 2017-10-02 09:00
Ok

**Comment by istarkov** [comment] 2017-10-02 09:00
Waiting for PR ;-)

**Closed** 2017-10-06 15:01 UTC
Labels: help wanted

**Comment by istarkov** [comment] 2017-10-06 15:14
#538 optimisations removed please test 0.26

**Comment by dlebedynskyi** [comment] 2017-10-06 18:42
> please test 0.26
Issue seem to be resolved. Thank you for the fix.

**Comment by DBjelovuk** [comment] 2019-02-21 18:15
Still getting this error when using `lifecycle`.
